sudo: false

cache:
    directories:
        - $HOME/.m2

jdk:
    - oraclejdk7

before_install:
    - git clone --depth 1 git://github.com/thehyve/transmart-travis.git ~/ts-travis
    - source ~/ts-travis/init.sh
    - source ~/ts-travis/grails_inline.sh
    - source ~/ts-travis/maven_dep.sh

install:
    - build_maven_dep $(travis_get_owner)/${PREFIX}transmart-core-api master core-api
    - make_inline_grails_dep $(travis_get_owner)/${PREFIX}transmart-core-db master core-db . transmart-core-db-tests

script:
    - grails refresh-dependencies --non-interactive
    - grails test-app --non-interactive --stacktrace
